import { Component, signal } from '@angular/core';
import { CountriesMapComponent, CountriesData, ChartSelectEvent } from 'countries-map';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CountriesMapComponent],
  templateUrl: './app.html',
  styleUrl: './app.css'
})
export class App {
  protected readonly title = signal('Countries Map Demo');

  protected readonly mapData = signal<CountriesData>({
    // Africa
    DZ: { value: 44, extra: { capital: 'Algiers' } },
    AO: { value: 33, extra: { capital: 'Luanda' } },
    BJ: { value: 12, extra: { capital: 'Porto-Novo' } },
    BW: { value: 2, extra: { capital: 'Gaborone' } },
    BF: { value: 21, extra: { capital: 'Ouagadougou' } },
    BI: { value: 12, extra: { capital: 'Gitega' } },
    CV: { value: 1, extra: { capital: 'Praia' } },
    CM: { value: 27, extra: { capital: 'Yaoundé' } },
    CF: { value: 5, extra: { capital: 'Bangui' } },
    TD: { value: 17, extra: { capital: "N'Djamena" } },
    KM: { value: 1, extra: { capital: 'Moroni' } },
    CD: { value: 92, extra: { capital: 'Kinshasa' } },
    CG: { value: 6, extra: { capital: 'Brazzaville' } },
    CI: { value: 27, extra: { capital: 'Yamoussoukro' } },
    DJ: { value: 1, extra: { capital: 'Djibouti' } },
    EG: { value: 102, extra: { capital: 'Cairo' } },
    GQ: { value: 1, extra: { capital: 'Malabo' } },
    ER: { value: 4, extra: { capital: 'Asmara' } },
    SZ: { value: 1, extra: { capital: 'Mbabane' } },
    ET: { value: 118, extra: { capital: 'Addis Ababa' } },
    GA: { value: 2, extra: { capital: 'Libreville' } },
    GM: { value: 2, extra: { capital: 'Banjul' } },
    GH: { value: 32, extra: { capital: 'Accra' } },
    GN: { value: 13, extra: { capital: 'Conakry' } },
    GW: { value: 2, extra: { capital: 'Bissau' } },
    KE: { value: 54, extra: { capital: 'Nairobi' } },
    LS: { value: 2, extra: { capital: 'Maseru' } },
    LR: { value: 5, extra: { capital: 'Monrovia' } },
    LY: { value: 7, extra: { capital: 'Tripoli' } },
    MG: { value: 28, extra: { capital: 'Antananarivo' } },
    MW: { value: 19, extra: { capital: 'Lilongwe' } },
    ML: { value: 21, extra: { capital: 'Bamako' } },
    MR: { value: 5, extra: { capital: 'Nouakchott' } },
    MU: { value: 1, extra: { capital: 'Port Louis' } },
    MA: { value: 37, extra: { capital: 'Rabat' } },
    MZ: { value: 32, extra: { capital: 'Maputo' } },
    NA: { value: 3, extra: { capital: 'Windhoek' } },
    NE: { value: 25, extra: { capital: 'Niamey' } },
    NG: { value: 206, extra: { capital: 'Abuja' } },
    RW: { value: 13, extra: { capital: 'Kigali' } },
    ST: { value: 1, extra: { capital: 'São Tomé' } },
    SN: { value: 17, extra: { capital: 'Dakar' } },
    SC: { value: 1, extra: { capital: 'Victoria' } },
    SL: { value: 8, extra: { capital: 'Freetown' } },
    SO: { value: 16, extra: { capital: 'Mogadishu' } },
    ZA: { value: 60, extra: { capital: 'Pretoria' } },
    SS: { value: 11, extra: { capital: 'Juba' } },
    SD: { value: 44, extra: { capital: 'Khartoum' } },
    TZ: { value: 62, extra: { capital: 'Dodoma' } },
    TG: { value: 8, extra: { capital: 'Lomé' } },
    TN: { value: 12, extra: { capital: 'Tunis' } },
    UG: { value: 46, extra: { capital: 'Kampala' } },
    ZM: { value: 19, extra: { capital: 'Lusaka' } },
    ZW: { value: 15, extra: { capital: 'Harare' } },
    // Asia
    AF: { value: 39, extra: { capital: 'Kabul' } },
    AM: { value: 3, extra: { capital: 'Yerevan' } },
    AZ: { value: 10, extra: { capital: 'Baku' } },
    BH: { value: 2, extra: { capital: 'Manama' } },
    BD: { value: 165, extra: { capital: 'Dhaka' } },
    BT: { value: 1, extra: { capital: 'Thimphu' } },
    BN: { value: 1, extra: { capital: 'Bandar Seri Begawan' } },
    KH: { value: 17, extra: { capital: 'Phnom Penh' } },
    CN: { value: 1412, extra: { capital: 'Beijing' } },
    CY: { value: 1, extra: { capital: 'Nicosia' } },
    GE: { value: 4, extra: { capital: 'Tbilisi' } },
    IN: { value: 1380, extra: { capital: 'New Delhi' } },
    ID: { value: 274, extra: { capital: 'Jakarta' } },
    IR: { value: 84, extra: { capital: 'Tehran' } },
    IQ: { value: 41, extra: { capital: 'Baghdad' } },
    JP: { value: 125, extra: { capital: 'Tokyo' } },
    JO: { value: 10, extra: { capital: 'Amman' } },
    KZ: { value: 19, extra: { capital: 'Astana' } },
    KW: { value: 4, extra: { capital: 'Kuwait City' } },
    KG: { value: 7, extra: { capital: 'Bishkek' } },
    LA: { value: 7, extra: { capital: 'Vientiane' } },
    LB: { value: 7, extra: { capital: 'Beirut' } },
    MY: { value: 32, extra: { capital: 'Kuala Lumpur' } },
    MV: { value: 1, extra: { capital: 'Malé' } },
    MN: { value: 3, extra: { capital: 'Ulaanbaatar' } },
    MM: { value: 54, extra: { capital: 'Naypyidaw' } },
    NP: { value: 30, extra: { capital: 'Kathmandu' } },
    KP: { value: 26, extra: { capital: 'Pyongyang' } },
    OM: { value: 5, extra: { capital: 'Muscat' } },
    PK: { value: 220, extra: { capital: 'Islamabad' } },
    PS: { value: 5, extra: { capital: 'Ramallah' } },
    PH: { value: 110, extra: { capital: 'Manila' } },
    QA: { value: 3, extra: { capital: 'Doha' } },
    SA: { value: 35, extra: { capital: 'Riyadh' } },
    SG: { value: 6, extra: { capital: 'Singapore' } },
    KR: { value: 52, extra: { capital: 'Seoul' } },
    LK: { value: 22, extra: { capital: 'Colombo' } },
    SY: { value: 18, extra: { capital: 'Damascus' } },
    TW: { value: 24, extra: { capital: 'Taipei' } },
    TJ: { value: 10, extra: { capital: 'Dushanbe' } },
    TH: { value: 70, extra: { capital: 'Bangkok' } },
    TL: { value: 1, extra: { capital: 'Dili' } },
    TR: { value: 84, extra: { capital: 'Ankara' } },
    TM: { value: 6, extra: { capital: 'Ashgabat' } },
    AE: { value: 10, extra: { capital: 'Abu Dhabi' } },
    UZ: { value: 34, extra: { capital: 'Tashkent' } },
    VN: { value: 98, extra: { capital: 'Hanoi' } },
    YE: { value: 30, extra: { capital: "Sana'a" } },
    // Europe
    AL: { value: 3, extra: { capital: 'Tirana' } },
    AD: { value: 1, extra: { capital: 'Andorra la Vella' } },
    AT: { value: 9, extra: { capital: 'Vienna' } },
    BY: { value: 9, extra: { capital: 'Minsk' } },
    BE: { value: 12, extra: { capital: 'Brussels' } },
    BA: { value: 3, extra: { capital: 'Sarajevo' } },
    BG: { value: 7, extra: { capital: 'Sofia' } },
    HR: { value: 4, extra: { capital: 'Zagreb' } },
    CZ: { value: 11, extra: { capital: 'Prague' } },
    DK: { value: 6, extra: { capital: 'Copenhagen' } },
    EE: { value: 1, extra: { capital: 'Tallinn' } },
    FI: { value: 6, extra: { capital: 'Helsinki' } },
    FR: { value: 67, extra: { capital: 'Paris' } },
    DE: { value: 83, extra: { capital: 'Berlin' } },
    GR: { value: 11, extra: { capital: 'Athens' } },
    HU: { value: 10, extra: { capital: 'Budapest' } },
    IS: { value: 1, extra: { capital: 'Reykjavik' } },
    IE: { value: 5, extra: { capital: 'Dublin' } },
    IT: { value: 60, extra: { capital: 'Rome' } },
    XK: { value: 2, extra: { capital: 'Pristina' } },
    LV: { value: 2, extra: { capital: 'Riga' } },
    LI: { value: 1, extra: { capital: 'Vaduz' } },
    LT: { value: 3, extra: { capital: 'Vilnius' } },
    LU: { value: 1, extra: { capital: 'Luxembourg' } },
    MT: { value: 1, extra: { capital: 'Valletta' } },
    MD: { value: 3, extra: { capital: 'Chișinău' } },
    MC: { value: 1, extra: { capital: 'Monaco' } },
    ME: { value: 1, extra: { capital: 'Podgorica' } },
    NL: { value: 17, extra: { capital: 'Amsterdam' } },
    MK: { value: 2, extra: { capital: 'Skopje' } },
    NO: { value: 5, extra: { capital: 'Oslo' } },
    PL: { value: 38, extra: { capital: 'Warsaw' } },
    PT: { value: 10, extra: { capital: 'Lisbon' } },
    RO: { value: 19, extra: { capital: 'Bucharest' } },
    RU: { value: 144, extra: { capital: 'Moscow' } },
    SM: { value: 1, extra: { capital: 'San Marino' } },
    RS: { value: 7, extra: { capital: 'Belgrade' } },
    SK: { value: 5, extra: { capital: 'Bratislava' } },
    SI: { value: 2, extra: { capital: 'Ljubljana' } },
    ES: { value: 47, extra: { capital: 'Madrid' } },
    SE: { value: 10, extra: { capital: 'Stockholm' } },
    CH: { value: 9, extra: { capital: 'Bern' } },
    UA: { value: 44, extra: { capital: 'Kyiv' } },
    GB: { value: 67, extra: { capital: 'London' } },
    VA: { value: 1, extra: { capital: 'Vatican City' } },
    // North America
    AG: { value: 1, extra: { capital: "Saint John's" } },
    BS: { value: 1, extra: { capital: 'Nassau' } },
    BB: { value: 1, extra: { capital: 'Bridgetown' } },
    BZ: { value: 1, extra: { capital: 'Belmopan' } },
    CA: { value: 38, extra: { capital: 'Ottawa' } },
    CR: { value: 5, extra: { capital: 'San José' } },
    CU: { value: 11, extra: { capital: 'Havana' } },
    DM: { value: 1, extra: { capital: 'Roseau' } },
    DO: { value: 11, extra: { capital: 'Santo Domingo' } },
    SV: { value: 6, extra: { capital: 'San Salvador' } },
    GD: { value: 1, extra: { capital: "Saint George's" } },
    GT: { value: 18, extra: { capital: 'Guatemala City' } },
    HT: { value: 11, extra: { capital: 'Port-au-Prince' } },
    HN: { value: 10, extra: { capital: 'Tegucigalpa' } },
    JM: { value: 3, extra: { capital: 'Kingston' } },
    MX: { value: 128, extra: { capital: 'Mexico City' } },
    NI: { value: 7, extra: { capital: 'Managua' } },
    PA: { value: 4, extra: { capital: 'Panama City' } },
    KN: { value: 1, extra: { capital: 'Basseterre' } },
    LC: { value: 1, extra: { capital: 'Castries' } },
    VC: { value: 1, extra: { capital: 'Kingstown' } },
    TT: { value: 1, extra: { capital: 'Port of Spain' } },
    US: { value: 331, extra: { capital: 'Washington D.C.' } },
    // South America
    AR: { value: 45, extra: { capital: 'Buenos Aires' } },
    BO: { value: 12, extra: { capital: 'Sucre' } },
    BR: { value: 213, extra: { capital: 'Brasília' } },
    CL: { value: 19, extra: { capital: 'Santiago' } },
    CO: { value: 51, extra: { capital: 'Bogotá' } },
    EC: { value: 18, extra: { capital: 'Quito' } },
    GY: { value: 1, extra: { capital: 'Georgetown' } },
    PY: { value: 7, extra: { capital: 'Asunción' } },
    PE: { value: 33, extra: { capital: 'Lima' } },
    SR: { value: 1, extra: { capital: 'Paramaribo' } },
    UY: { value: 3, extra: { capital: 'Montevideo' } },
    VE: { value: 28, extra: { capital: 'Caracas' } },
    // Oceania
    AU: { value: 26, extra: { capital: 'Canberra' } },
    FJ: { value: 1, extra: { capital: 'Suva' } },
    KI: { value: 1, extra: { capital: 'Tarawa' } },
    MH: { value: 1, extra: { capital: 'Majuro' } },
    FM: { value: 1, extra: { capital: 'Palikir' } },
    NR: { value: 1, extra: { capital: 'Yaren' } },
    NZ: { value: 5, extra: { capital: 'Wellington' } },
    PW: { value: 1, extra: { capital: 'Ngerulmud' } },
    PG: { value: 9, extra: { capital: 'Port Moresby' } },
    WS: { value: 1, extra: { capital: 'Apia' } },
    SB: { value: 1, extra: { capital: 'Honiara' } },
    TO: { value: 1, extra: { capital: "Nuku'alofa" } },
    TV: { value: 1, extra: { capital: 'Funafuti' } },
    VU: { value: 1, extra: { capital: 'Port Vila' } }
  });

  protected readonly selectedCountry = signal<string | null>(null);

  protected onChartReady(): void {
    console.log('Map loaded successfully');
  }

  protected onChartSelect(event: ChartSelectEvent): void {
    this.selectedCountry.set(event.selected ? event.country : null);
    console.log('Selected:', event);
  }
}
